### PR TITLE
Github provider "Invalid Account"

### PR DESCRIPTION
**Pull request by jehiah**
I'm having trouble trying out oauth2 proxy with the Github provider as well. I'm able to get to the Github login page, log in, and then get redirected to the callback, but then I end up at this page:

image

The URL looks like:
`https://myapp.com/oauth2/callback?code=<some_code>&state=%2Foauth2`

Here's my configuration
```ini
request_logging = true
client_id = "<client_id>"
client_secret = "<client_secret>"
cookie_secret = "fadlkfjdlkaksfldkasfad"
provider = "github"
upstreams = [
  "http://127.0.0.1:8080/"
]
```

And logs
```
2015/06/05 20:28:46 oauthproxy.go:121: Cookie settings: secure (https):true httponly:true expiry:168h0m0s domain:<default>
2015/06/05 20:28:46 main.go:128: listening on 127.0.0.1:4180
2015/06/05 20:29:02 oauthproxy.go:260: http: named cookie not present
104.218.136.246 - - [05/Jun/2015:20:29:02 +0000] ec2-99-6-167-68.compute-1.amazonaws.com GET - "/oauth2" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" 403 2250 0.001
2015/06/05 20:29:03 oauthproxy.go:260: http: named cookie not present
104.218.136.246 - - [05/Jun/2015:20:29:03 +0000] ec2-99-6-167-68.compute-1.amazonaws.com GET - "/favicon.ico" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" 403 2255 0.000
104.218.136.246 - - [05/Jun/2015:20:29:04 +0000] ec2-99-6-167-68.compute-1.amazonaws.com GET - "/oauth2/start?rd=%2Foauth2" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" 302 277 0.000
2015/06/05 20:29:05 validator.go:78: validating: is mightyguava@gmail.com valid? false
2015/06/05 20:29:05 oauthproxy.go:286: ErrorPage 403 Permission Denied Invalid Account
104.218.136.246 - - [05/Jun/2015:20:29:05 +0000] ec2-99-6-167-68.compute-1.amazonaws.com GET - "/oauth2/callback?code=633ec61cad195150d227&state=%2Foauth2" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" 403 338 0.100
2015/06/05 20:29:05 oauthproxy.go:260: http: named cookie not present
104.218.136.246 - - [05/Jun/2015:20:29:05 +0000] ec2-99-6-167-68.compute-1.amazonaws.com GET - "/favicon.ico" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" 403 2255 0.000
```

Don't have the unmarshalling problem from https://github.com/bitly/oauth2_proxy/issues/108.

### CODE REVIEW

**Comment by jehiah** [comment]
@mightyguava I've pushed up a change that should handle the case you have where a user is part of an org but not a team. Can you validate that this works for you?

**Comment by mightyguava** [comment]
Yup. It is working for me. Thanks!

**Comment by jehiah** [comment]
Yay! Thanks for the confirmation.

**Comment by ajsharp** [comment]
Still seeing this issue. To clarify, the desired behavior that I'd like to see, and that I think OP was hoping for, was that, if I specify a github org, that means I'm saying I want all users who have access to that org to have access here, without specifying an email file. I believe this is how the google apps integration works if you specify a domain, right?

**Comment by ajsharp** [comment]
However, I'm using the latest stable release, not sure if that has the 13e8292

**Pull request merged**
