### PR TITLE
providers: add OpenID Connect provider

### PR DESCRIPTION
**Pull request by philips**
See the README for usage with Dex or any other OIDC provider.

This has only been tested against CoreOS Dex but should work against
other providers like Google, Facebook, etc as well.

To try it out see the improved Dex docs here: https://github.com/coreos/dex/pull/176

### CODE REVIEW

**Comment by philips** [comment]
Quick demo video: https://www.youtube.com/watch?v=cbiAhIUl8Hg&feature=youtu.be

**Comment by jehiah** [comment]
@philips thanks! This sounds great :tada: I'd like to land this feature separately from the style changes so i've merged #164. Can you rebase this?

I'll familiarize myself with OIDC and give you some feedback here shortly =)

**Comment by philips** [comment]
@jehiah rebased. I would like @bobbyrullo or @bcwaldon to review too since this is the first time I have used the go-oidc library.

**Comment by philips** [comment]
ping @bobbyrullo @bcwaldon @jehiah

**Comment by bobbyrullo** [comment]
sorry, not been keeping up with Github notifications very well. Taking a look now.

**Comment by emmanuel** [comment]
Is this likely to get merged into mainline? I see that CoreOS is maintaining a fork at https://github.com/coreos/oauth2_proxy which looks like it includes this functionality. If I want to use the proxy with OIDC today, I'm wondering if I should focus on CoreOS' fork, or on this upstream original.

**Comment by philips** [comment]
cc @ericchiang

**Comment by ericchiang** [comment]
Yeah I can take a crack at revamping the PR.

**Comment by gtaylor** [comment]
Is there anything we can do to help get this merged?

**Comment by ericchiang** [comment]
Updated PR here https://github.com/bitly/oauth2_proxy/pull/389

**Comment by philips** [comment]
Closed in favor of #389

**Pull request closed without merging**
