### PR TITLE
Page defaults to Google sign in

### PR DESCRIPTION
**Pull request by jehiah**
Hi,
 Thanks for solving the previous request as i said i am very new to GO, my aim is to have Nginx authenticate via github

as of now i have nginx serving only the default home page, have enabled self signed certificate to test the authentication
my nginx config is as follows
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;
        listen 443 ssl;

        server_name ec2-52-25-160-240.us-west-2.compute.amazonaws.com;
        root /usr/share/nginx/html;
        index index.html index.htm;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        add_header Strict-Transport-Security max-age=1209600;
        location / {
                proxy_pass http://127.0.0.1:4180;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
                proxy_connect_timeout 1;
                proxy_send_timeout 30;
                proxy_read_timeout 30;
            }

and Oauth_proxy is running as follows:  ./oauth2_proxy --upstream=https://127.0.0.1 --cookie-secret=secret --cookie-secure=true --client-id=2**********3 --client-secret=Aef***********a

my page always greets me with login with google account and also gives 404 after that

i want to start using the github credentials for logging please help, this is very critical

my call back url is 
https://ec2-52-25-160-240.us-west-2.compute.amazonaws.com/oauth2/callback

### CODE REVIEW

**Comment by jehiah** [comment]
@dbiswas1 I've added some more specific logging around failed requests to the provider (github in your case). Please build a new version of `oauth2_proxy` and let me know what errors you get now.

**Comment by dbiswas1** [comment]
Thanks a lot, i will try this and inform you i am trying to implement this
a solution would be great if i can make it, will update about the progress

Thx
Deepak

On Mon, Jun 8, 2015 at 6:37 AM, Jehiah Czebotar <notifications@github.com>
wrote:

> @dbiswas1 <https://github.com/dbiswas1> I've added some more specific
> logging around failed requests to the provider (github in your case).
> Please build a new version of oauth2_proxy and let me know what errors
> you get now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitly/oauth2_proxy/pull/108#issuecomment-109819821>.
>



-- 
Regards
Deepak Biswas

**Comment by dbiswas1** [comment]
Now i have a weird error, not sure how will i make this work
116.202.116.191 - - [15/Jul/2015:17:33:57 +0000] 52.27.38.143 GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0" 302 255 0.000
2015/07/15 17:33:59 github.go:180: got 200 from "https://api.github.com/user/emails?access_token=*******" [{"email":"deepak.biswas19@gmail.com","primary":true,"verified":true}]
2015/07/15 17:33:59 oauthproxy.go:444: 127.0.0.1:39697 ("116.202.116.191") Permission Denied: "de********19@gmail.com" is unauthorized
2015/07/15 17:33:59 oauthproxy.go:270: ErrorPage 403 Permission Denied Invalid Account

i checked form the browser with the credentials and i am authorized but it fails here

Thx
Deepak

**Comment by dbiswas1** [comment]
Can you please reopen this, so that i can get some help i am trying from longtime to setup oAuth2

**Pull request merged**
