### PR TITLE
Adds Azure AD provider

### PR DESCRIPTION
**Pull request by eelcocramer**
Like mentioned in #114.

To get the mail address of a authenticated user from the Microsoft Graph API it is needed to access Azure AD protected resource (ie. `https://graph.windows.net`). For this a `resource`  header needs to be added to redeem request.

This PR adds the following command line options:

```
---azure-tenant <string>: to go to a tenant-specific Azure AD endpoint. (defaults to the "common" endpoint)
---resource <string>: the url of a protected resource.
```

### CODE REVIEW

**Comment by eelcocramer** [comment]
Is something holding this PR back?

**Comment by jehiah** [comment]
@eelcocramer sorry, this dropped off my radar. Thanks for expanding the provider list with Azure! The changes you made all look good (and I assume you are already using this in a production environment?)

Can you squash down to a single commit before we merge this in?

**Comment by eelcocramer** [comment]
I've squashed the commits.

I'm not using the code in production yet but a proxy with this code is running in our dev environment and is used there.

**Comment by jehiah** [comment]
merged as 10f47e325b782a60b8689653fa45360dee7fbf34

**Pull request closed without merging**
