### PR TITLE
adding option to skip provider button sign_in page

### PR DESCRIPTION
**Pull request by rahdjoudj**
An option to skip the sign_in page and redirect instead to the start page.
That change is for users experience only. My users are fully aware that they will use their google account. They want to avoid any extra steps.

### CODE REVIEW

**Comment by ktheory** [comment]
:+1: to this feature. I'd use it too.

Thanks, @rahdjoudj

**Comment by nhumphreys** [comment]
:+1: great feature!

**Comment by rahdjoudj** [comment]
It's busted since last commit. I'll fix that quickly.
Cheers,

**Comment by rahdjoudj** [comment]
Here we go ! back on track :)

**Pull request merged**
