### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by odedlaz**
The Dockerfile fetches the latest GitHub release and builds it.
This might be better than building straight from source, and makes the build process IMO.

### CODE REVIEW

**Comment by underyx** [comment]
👎, if I `git checkout` an old version and run `docker build .`, I want (and would expect) that old version to be built.

**Comment by ahmetb** [comment]
@odedlaz would you consider editing this to just build from the source code? It would be easier to take in.

**Comment by dstroot** [comment]
Take a look at this alternative: https://github.com/bitly/oauth2_proxy/pull/372

**Comment by pataquets** [comment]
+1 for [Automated Builds](https://docs.docker.com/docker-hub/builds/) straight from source on Docker Hub.

**Pull request closed without merging**
