### PR TITLE
WIP: LetsEncrypt Support via rsc.io/letsencrypt

### LINKED ISSUE #313: autocert / letsencrypt integration
Would be extremely useful for oauth2_proxy to automatically grab SSL certificates from LetsEncrypt if asked to. I'm willing to implement this, if the maintainers think it's a good / mergable idea :)

### PR DESCRIPTION
**Pull request by fortytw2**
Not finished yet, but opening a WIP PR keeps the work I'm doing on this open 

Allows for automatic fetching and validation of LetsEncrypt SSL certs with a few quick settings :) 

TODO: 
- [ ] Update documentation
- [ ] Really test that it works (haven't done yet)
- [ ] Ensure HTTP -> HTTPS redirects when using LetsEncrypt

This will close #313

### CODE REVIEW

**Comment by devoid** [comment]
Hey @fortytw2 it looks like you almost got this working! Now that the ACME stuff is in golang.or/x/crypt/acme I was wondering if i should try to update this PR?

Was there anything blocking it? (Difficulty testing or concerns about the 'alpha' dependency?)

**Comment by jehiah** [comment]
@devoid Yes, `golang.org/x/crypt/acme` is the preferred way we should adopt letsencrypt support at the moment.

**Comment by fortytw2** [comment]
👋 @devoid I think this PR would work, never got a chance to actually test it out though, I went with another solution in the end. Feel free to take it over if you want to

**Comment by devoid** [comment]
@jehiah I've uploaded a new PR; I was wondering if this is sufficient or if I should change something with that PR?

**Comment by fortytw2** [comment]
Going to defer to @devoid's PR entirely and close this one

**Pull request closed without merging**
