### PR TITLE
feat: Support proxying WebSocket connections.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by ploxiln** [comment]
there's also #201 and #145 (and others), and those two are "hundreds of lines added" rather than "thousands of lines added"

**Comment by ploxiln** [comment]
oh, looks like you're copying in all dependencies. this project doesn't do that, it locks to a specific tag or commit in Godeps but does not copy them in

**Comment by chirino** [comment]
Dropped the vendoring stuff, using Godeps now.

**Comment by chirino** [comment]
Should I close this out? Seem the openshift fork has added websocket support and that's good enough for me.  I close this out soon if I don't here back.

**Comment by chirino** [comment]
Seems there is no interest.

**Pull request closed without merging**
